[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"

[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"